name: Python

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit test
        working-directory: python/tests
        run: |
          export PYTHONPATH=$PYTHONPATH:../src
          coverage run -m pytest
          coverage xml
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CI: true
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}