name: Scala

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Compile sources
        working-directory: scala
        run: sbt 'clean' 'compile' 'test:compile'
        env:
          REPO_TOKEN: ${{ secrets.GH_EXPLOIT_TOKEN }}

      - name: Run unit tests
        working-directory: scala
        run: sbt 'test'

      - name: Measure test cover
        working-directory: scala
        run: |
          sbt jacoco
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/scala-2.13/jacoco/report/jacoco.xml
        env:
          CI: true
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
